---
# Autofs
autofs_service.install: True
autofs_service.enable: True
nfs_kernel_tuning: True

autofs_mount_points:
  - data
  - usrlocal

autofs_conf_files:
  data:
    - share       -rw,hard,nosuid         {{ groups['nfs'][0] }}:/data/share
  usrlocal:
    - /opt/galaxy        -rw,hard,nosuid         {{ groups['nfs'][0] }}:/opt/galaxy


# HTCondor
condor_role: central-manager
condor_host: "{{ groups['central_manager'][0] }}" 
condor_password: '{{ condor_pass }}' # secret_group_vars/htconodor.yml
condor_allow_write: "*"
condor_daemons:
  - COLLECTOR
  - MASTER
  - NEGOTIATOR
  - SCHEDD
condor_allow_negotiator: $(ALLOW_WRITE)
condor_allow_administrator: $(ALLOW_NEGOTIATOR)
condor_network_interface: eth0
condor_fs_domain: usegalaxy.it
condor_uid_domain: usegalaxy.it
condor_enforce_role: false
