---
# Autofs
autofs_service.install: True
autofs_service.enable: True
nfs_kernel_tuning: True

autofs_mount_points:
  - data


autofs_conf_files:
  data:
    - share       -rw,hard,nosuid      172.30.16.115:/data/share
  discontinued:
              
  
  userlocal:

# HTCondor
condor_host: "localhost"
condor_allow_write: "*"
condor_daemons:
    - COLLECTOR
    - MASTER
    - NEGOTIATOR
    - SCHEDD
condor_allow_negotiator: $(ALLOW_WRITE)
condor_allow_administrator: "$(ALLOW_NEGOTIATOR)"
