---
# Autofs
usegalaxy_eu_autofs_mounts:
 - data

# HTCondor
condor_host: "localhost"
condor_allow_write: "*"
condor_daemons:
    - COLLECTOR
    - MASTER
    - NEGOTIATOR
    - SCHEDD
condor_allow_negotiator: $(ALLOW_WRITE)
condor_allow_administrator: "$(ALLOW_NEGOTIATOR)"
condor_network_interface: eth1 
