---
# Autofs
usegalaxy_eu_autofs_mounts:
 - data

# HTCondor
condor_host: "condor-cm.galaxyproject.eu"
condor_allow_write: "10.5.68.0/24, 132.230.68.0/24, 132.230.223.0/24, *.bi.uni-freiburg.de"
condor_daemons:
    - COLLECTOR
    - MASTER
    - NEGOTIATOR
condor_allow_negotiator: $(ALLOW_WRITE)
condor_allow_administrator: "$(ALLOW_NEGOTIATOR)"
condor_network_interface: ens802f0.2368
condor_extra: |
  MASTER_UPDATE_INTERVAL = 150
  CLASSAD_LIFETIME = 300
  NEGOTIATOR_INTERVAL = 15
  NEGOTIATOR_UPDATE_INTERVAL = 100
  JOB_START_COUNT = 250
  JOB_START_DELAY = 0
  NEGOTIATOR_POST_JOB_RANK = isUndefined(RemoteOwner) * (10000 - TotalLoadAvg)
