---
- name: Postgresql DB
  hosts: database
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/db-main.yml # DB URL + some postgres stuff
  pre_tasks:
    - name: Install pgdg repository package (RedHat)
      yum:
        name: >-
          https://download.postgresql.org/pub/repos/yum/reporpms/{{ postgresql_pgdg_shortfamilies[ansible_distribution]
            | default("EL") }}-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-{{
            postgresql_pgdg_families[ansible_distribution] | default("redhat") }}-repo-latest.noarch.rpm
        disable_gpg_check: true
    - name: install acl and psycopg2 packages
      package:
        name: ["acl", "python3-psycopg2"]
      become: true
  roles:
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
