
---
- name: UseGalaxy.eu
  hosts: database
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/db-main.yml    # DB URL + some postgres stuff
    - secret_group_vars/all.yml    # DB URL + some postgres stuff
    - group_vars/gxconfig.yml   # DB URL + some postgres stuff
  tasks:
    - name: delete exysting db
      postgresql_db:
        name: galaxy
        state: absent
        owner: galaxy
        login_password: "{{ _galaxy_db_pass }}" 
