---
- name: Mount NFS
  hosts: sn06
  become: true
  become_user: root
  tasks:
    - name: Mount network share
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.mountpoint }}"
        fstype: nfs
        state: mounted
      with_items:
        - { src: "{{ nfs_server_ip }}:/data/share", mountpoint: /data/share } # nfs-server IP
        - { src: "{{ nfs_server_ip }}:/opt/galaxy", mountpoint: /opt/galaxy }
