---
- name: Proxy internal
  hosts: proxy-internal
  become: true
  vars:
    hostname: cloud-90-147-102-77.cloud.ba.infn.it
    rabbitmq_version: "3.8.26"
  pre_tasks:
    - name: install epel
      yum:
        name: epel-release
    - name: install erlang repository
      shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash
    - name: install erlang 
      yum:
        name: erlang-23.3.4
        state: present

  vars_files:
    - group_vars/all.yml
      #    - secret_group_vars/pulsar.yml     # Pulsar + MQ Connections
    - secret_group_vars/all.yml
  collections:
    - devsec.hardening
      #  pre_tasks:
      #    - name: intall epel release
      #      yum:
      #        name: 
      #          - epel-release
      #          - python-pip
      #          - openssl-devel
      #          - python-devel
      #          - libffi-devel
      #    - name: install latest pip
      #      pip: 
      #        name: pip
      #        state: latest
      #    - name: install pip packeages to authenticate to github 
      #      pip:
      #        name:
      #          - pyOpenSSL 
      #          - ndg-httpsclient
      #          - pyasn1
  roles:
    - hostname
      #    - usegalaxy-eu.dynmotd
    - geerlingguy.repo-epel
    - geerlingguy.rabbitmq
      #   - hxr.admin-tools
      #  - influxdata.chrony
      #    - hxr.monitor-email
      #    - linuxhq.yum_cron
    - jasonroyle.rabbitmq
    - galaxyproject.nginx
      #   - dj-wasabi.telegraf
    #- os_hardening
    #- nginx_hardening
    #- ssh_hardening
##TODO add 
#yum update -y nss curl libcurl

