---
- name: Replica VM
  hosts: replica
  become: true
  become_user: root
  vars_files:
    - secret_group_vars/db-main.yml # DB URL + some postgres stuff
    - group_vars/database.yml  
  pre_tasks:
    - name: install acl and psycopg2 packages
      package:
        name: ["acl", "python3-psycopg2"]
      become: true
  roles:
    - galaxyproject.postgresql
    - role: usegalaxy-it.postgresql_replication
      become: true
      vars: 
        replication_role: standby
      when: postgres_replication