---
- copy:
    content: |
        #!/bin/bash
        TIMES=$(mktemp)

        timeout 3m pdsh -g cloud -l centos 'time timeout 1m  ls /data/dnb03/galaxy_db/' 1>/dev/null 2> $TIMES
        cat $TIMES | grep real | sed 's/\([0-9]*\)m\([0-9.]*\)s/\1\t\2/g' | awk '{print $1"\t"$3 * 60 + $4}' | sed 's/://g' | awk '{print "network-disk-access-time,server="$1",disk=Isilon_dnb03_from_cluster seconds="$2}'

        timeout 3m pdsh -g cloud -l centos 'time timeout 1m  ls /data/dnb05/galaxy_db/' 1>/dev/null 2> $TIMES
        cat $TIMES | grep real | sed 's/\([0-9]*\)m\([0-9.]*\)s/\1\t\2/g' | awk '{print $1"\t"$3 * 60 + $4}' | sed 's/://g' | awk '{print "network-disk-access-time,server="$1",disk=AF400_dnb01_from_cluster seconds="$2}'

        timeout 3m pdsh -g cloud -l centos 'time timeout 1m  ls /data/gxkey/server/' 1>/dev/null 2> $TIMES
        cat $TIMES | grep real | sed 's/\([0-9]*\)m\([0-9.]*\)s/\1\t\2/g' | awk '{print $1"\t"$3 * 60 + $4}' | sed 's/://g' | awk '{print "network-disk-access-time,server="$1",disk=AF400_ws01_from_cluster seconds="$2}'

        rm -f $TIMES
    dest: /usr/bin/monitor-network-disk-access-time
    owner: root
    group: root
    mode: 0755

- set_fact:
    plugin_config_monitor_network_disk_access:
      monitor_network_disk_access:
        plugin: "exec"
        config:
          - commands = ["/usr/bin/monitor-network-disk-access-time"]
          - timeout = "3m"
          - data_format = "influx"
          - interval = "30m"

- set_fact:
        telegraf_plugins_extra: "{{ telegraf_plugins_extra | combine(plugin_config_monitor_network_disk_access) }}"
