---
# This is a file of variables that will be processed in job_conf.yml.j2
# This is needed, because it contains other variables

galaxy_jobconf:
  plugin_workers: 8
  handlers:
    count: "{{ galaxy_systemd_handlers }}"
    assign_with: db-skip-locked
    max_grab: 16
    ready_window_size: 32
  plugins:
    #- id: drmaa
    #load: galaxy.jobs.runners.drmaa:DRMAAJobRunner
    #workers: 3
    - id: condor
      load: galaxy.jobs.runners.condor:CondorJobRunner
    - id: local
      load: galaxy.jobs.runners.local:LocalJobRunner
    - id: pulsar_embedded
      load: galaxy.jobs.runners.pulsar:PulsarEmbeddedJobRunner
      pulsar_config: "{{ galaxy_config_dir }}/pulsar_app.yml"

    - id: pulsar_eu_it05
      load: galaxy.jobs.runners.pulsar:PulsarMQJobRunner
      params:
        amqp_url: "pyamqp://pulsar_it05:{{ rabbitmq_password_pulsar_it05 }}@mq.galaxyproject.eu:5671//pulsar/pulsar_it05?ssl=1"
        galaxy_url: "https://usegalaxy.eu"
        manager: production
        amqp_acknowledge: "true"
        amqp_ack_republish_time: 300
        amqp_consumer_timeout: 2.0
        amqp_publish_retry: "true"
        amqp_publish_retry_max_retries: 60
