private_token: {{ pulsar_private_token }}
persistence_directory: /data/share/persisted_data
staging_directory: /data/share/staging
tool_dependency_dir: /data/share/tools/

managers:
  _default_:
    type: queued_condor
