---

- name: Create users
  block:

    - name: Create Galaxy group
      group:
        name: "{{ galaxy_group.name | default(galaxy_group) }}"
        gid: "{{ galaxy_group.gid | default(omit) }}"
        system: "{{ galaxy_group.system | default(galaxy_user.system) | default('true') }}"
        local: "{{ galaxy_group.local | default(galaxy_user.local) | default(omit) }}"

    - name: Create Galaxy user
      user:
        name: "{{ galaxy_user.name | default(galaxy_user) }}"
        uid: "{{ galaxy_user.uid | default(omit) }}"
        group: "{{ (galaxy_group | default({})).name | default(galaxy_group) | default(omit) }}"
        comment: "{{ galaxy_user.comment | default('Galaxy server') }}"
        create_home: "{{ galaxy_user.create_home | default('true') }}"
        home: "{{ galaxy_user.home | default(omit) }}"
        shell: "{{ galaxy_user.shell | default(omit) }}"
        system: "{{ galaxy_user.system | default('true') }}"
        local: "{{ galaxy_user.local | default(omit) }}"
